deploy_wordpress_name: "xavki"
deploy_wordpress_url: "xavki.swarm"
deploy_wordpress_mariadb_user: "mariadb_xavki"
deploy_wordpress_mariadb_password: "monpassword"
deploy_wordpress_container_port: "80"