---


- name: cr√©ation du user devops
  user:
    name: devops
    shell: /bin/bash
    groups: sudo
    append: yes
    password: "{{ 'password' | password_hash('sha512') }}"

- name: Add devops user to the sudoers
  copy:
    dest: "/etc/sudoers.d/devops"
    content: "devops  ALL=(ALL)  NOPASSWD: ALL"

- name: Deploy SSH Key
  authorized_key:
    user: devops
    key: "{{ lookup('file', '/tmp/xavki.pub') }}"
    state: present
